name: DevSecOps CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r secure-ci-basics/requirements.txt

    - name: Run app
      run: |
        python secure-ci-basics/src/app.py

    - name: Secret Scan with GitLeaks
      uses: zricethezav/gitleaks-action@v2.3.3

    - name: Lint Python Code
      run: |
        pip install flake8
        flake8 secure-ci-basics/src/ || true

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget -y
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.47.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.47.0_Linux-64bit.deb

    - name: Run Trivy Vulnerability Scan
      run: |
        trivy fs --exit-code 0 .
